"""Database query helpers for the Scylla ML backend.

Extracted from ml_model.py: shared database functions used across
multiple endpoints and walkforward logic.
"""
import sqlite3
import time
import datetime
import logging
import pandas as pd

try:
    from ..config.constants import DB_PATH
except ImportError:
    from config.constants import DB_PATH

logger = logging.getLogger("scylla.ml_model")


def _execute_with_retry(func, max_retries=5, initial_delay=0.1):
    """Execute a database operation with retry logic for SQLite locking."""
    delay = initial_delay
    for attempt in range(max_retries):
        try:
            return func()
        except sqlite3.OperationalError as e:
            if "locked" in str(e).lower() and attempt < max_retries - 1:
                time.sleep(delay)
                delay *= 2  # Exponential backoff
            else:
                raise
    raise sqlite3.OperationalError("Max retries exceeded")


def _fetch_trades_from_db(query: str, params: list) -> pd.DataFrame:
    conn = sqlite3.connect(DB_PATH)
    try:
        return pd.read_sql_query(query, conn, params=params)
    finally:
        conn.close()


def get_real_trades(conn, **filters) -> pd.DataFrame:
    """
    Shared query helper that pulls options_trades.
    Default is is_synthetic = 0 (real scanner output). Pass synthetic=True to
    pull the Black-Scholes–grounded synthetic dataset generated by
    seed_grounded_real_options.py (used by the Phase A verification script
    to validate the model + strategy pipeline end-to-end on a known-positive
    expected-value universe).
    """
    synthetic = bool(filters.pop("synthetic", False))
    query = f"SELECT * FROM options_trades WHERE is_synthetic = {1 if synthetic else 0}"
    params = []
    for k, v in filters.items():
        query += f" AND {k} = ?"
        params.append(v)
    query += " ORDER BY timestamp ASC"
    return pd.read_sql_query(query, conn, params=params)


def get_dataset_stats(use_synthetic: bool = True) -> dict:
    """Lightweight dataset span probe.

    Returns MIN/MAX timestamp + COUNT for rows matching the given is_synthetic flag.
    No row payload — just aggregates.

    Args:
        use_synthetic: If True, count synthetic rows (is_synthetic=1);
                       otherwise count real rows (is_synthetic=0).

    Returns:
        dict with keys: data_start, data_end, data_span_days, data_count,
                        is_synthetic_filter.
    """
    conn = sqlite3.connect(DB_PATH)
    try:
        flag = 1 if use_synthetic else 0
        row = conn.execute(
            "SELECT MIN(timestamp), MAX(timestamp), COUNT(*) FROM options_trades WHERE is_synthetic = ?",
            (flag,),
        ).fetchone()
    finally:
        conn.close()
    if not row or row[0] is None or row[1] is None:
        return {
            "data_start": None,
            "data_end": None,
            "data_span_days": 0,
            "data_count": 0,
            "is_synthetic_filter": bool(use_synthetic),
        }
    ts_min_str, ts_max_str, count = row[0], row[1], int(row[2])
    data_start = ts_min_str[:10] if len(ts_min_str) >= 10 else ts_min_str
    data_end = ts_max_str[:10] if len(ts_max_str) >= 10 else ts_max_str
    try:
        d_min = datetime.datetime.strptime(data_start, "%Y-%m-%d").date()
        d_max = datetime.datetime.strptime(data_end, "%Y-%m-%d").date()
        data_span_days = (d_max - d_min).days
    except Exception:
        data_span_days = 0
    return {
        "data_start": data_start,
        "data_end": data_end,
        "data_span_days": int(data_span_days),
        "data_count": count,
        "is_synthetic_filter": bool(use_synthetic),
    }
